vulkan-198[2]: Update Vulkan cereal registry to upstream 1.2.198.
This merges the upstream 1.2.198 registry into emu-master-dev
branch.

Change-Id: I6d996641aacf5fcad81ce7362e9221f3fcd46d54

diff --git a/android/android-emugl/host/libs/libOpenglRender/vulkan-registry/config/optimize-pdf b/android/android-emugl/host/libs/libOpenglRender/vulkan-registry/config/optimize-pdf
--- a/android/android-emugl/host/libs/libOpenglRender/vulkan-registry/config/optimize-pdf
+++ b/android/android-emugl/host/libs/libOpenglRender/vulkan-registry/config/optimize-pdf
@@ -68,9 +68,11 @@ fi
 # -dProcessColorModel=/DeviceGray \
 # -dColorConversionStrategy=/Gray \
 
+ERRFILE=$FILE_BASENAME-ERRS.optimize
 "$GS" -q -dNOPAUSE -dBATCH -dSAFER -dNOOUTERSAVE \
   -sDEVICE=pdfwrite \
   -dPDFSETTINGS=/prepress \
+  -dPrinted=false \
   -dCannotEmbedFontPolicy=/Warning \
   -dDownsampleColorImages=$DOWNSAMPLE_IMAGES \
   -dColorImageResolution=$IMAGE_DPI \
@@ -79,6 +81,19 @@ fi
   -dDownsampleMonoImages=$DOWNSAMPLE_IMAGES \
   -dMonoImageResolution=$IMAGE_DPI \
   -sOutputFile="$FILE_OPTIMIZED" \
-  "$FILE" $FILE_PDFMARK
+  "$FILE" $FILE_PDFMARK 2> $ERRFILE
 
-exit 0
+status=$?
+if test $status -ne 0 ; then
+    echo "$0: $GS return status = $status, aborting"
+elif grep -q Error $ERRFILE ; then
+    echo "$0: $GS succeeded but found Error in $ERRFILE (follows), aborting"
+    echo '---------- Errors from $GS ----------'
+    grep Error $ERRFILE
+    echo '-------------------------------------'
+    status=1
+else
+    rm -f $ERRFILE
+fi
+
+exit $status
